### ISSUE TITLE
[Documentation] Tell users to switch to integrated graphics

### ISSUE THREAD

**Issue by aindriu80** [AdnanHodzic/auto-cpufreq#216]
I have been using auto-cpufreq on my XPS 15 9550 with Pop OS for a while but incredibly I had forgotten to switch from Nvidia discrete graphics to integrated graphics!  The difference is huge, maybe it's a bit too obvious but I have been using Windows mostly before.  Maybe it should be mentioned in the auto-cpufreq documentation.

![Screenshot from 2021-07-13 21-18-35](https://user-images.githubusercontent.com/8885837/125520120-0502a37b-c733-4df7-bbb2-16890851a4fb.png)

**Comment by AdnanHodzic** [comment]
With [v1.7.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/v1.7.0) it's now possible to manually define some of the settings instead of leaving everything to be picked up automatically. Could you try tweaking some of the [available options](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq) and report back on how that worked for you? Thanks

**Comment by AdnanHodzic** [comment]
> Maybe it should be mentioned in the auto-cpufreq documentation

Since I'm very limited with available time to do this myself, if you or anyone else wants to give it a try in implementing this functionality, please give it a try and [contribute to the project](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution) and you will be credited for your work as part of [future release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

In meantime closing the issue due to inactivity.
