### ISSUE TITLE
[feature request] Set max/min allowed frequency

### ISSUE THREAD

**Issue by MithicSpirit** [AdnanHodzic/auto-cpufreq#309]
It would be nice to add options to set the min/max frequencies on AC or battery since these are available on tlp.
(Continued from #297)

**Comment by AdnanHodzic** [comment]
It would be great to have this functionality and it would be ideal for the [config file](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq). 

Since I'm very limited with available time to do this myself, if you or anyone else wants to give it a try in implementing this functionality, please give it a try and [contribute to the project](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution).

**Comment by varaki** [comment]
#324

**Comment by AdnanHodzic** [comment]
This issue has now been resolved as part of [v1.9.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases).
