### ISSUE TITLE
[Request] Add update command

### ISSUE THREAD

**Issue by ariasmn** [AdnanHodzic/auto-cpufreq#341]
Currently, as discussed in #340 , for those that installed auto-cpufreq using the `auto-cpufreq-installer`, the update needs to be done manually, by downloading the new release and installing again.

Implemeting a new command, like `auto-cpufreq --update` to automatically do so would be a nice feature.

**Comment by AdnanHodzic** [comment]
Since I'm very limited with available time to do this myself, if you or anyone else wants to give it a try in implementing this functionality, please give it a try and [contribute to the project](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution) and you will be credited for your work as part of [future release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

**Comment by cosmos1721** [comment]
hey @AdnanHodzic 
can i work on this issue?

**Comment by AdnanHodzic** [comment]
@cosmos1721 please do, and once you have something please create a PR as I refered to above.

**Comment by AdnanHodzic** [comment]
Thanks to @cosmos1721 contribution, `--update` feature added as part of #535 has already been merged to `master` branch and will be part of upcoming v1.9.9 release. 

Hence closing the issue.
