### ISSUE TITLE
Error on auto cpu freq on PopOs

### ISSUE THREAD

**Issue by Eshu100** [AdnanHodzic/auto-cpufreq#414]
My son has a laptop from system76 with PopOs. He want to install auto-cpu freq but when he does that he gets this error

Failed to start power-profiles-daemon.service: Unit power-profiles-daemon.service not found.

Someone told me there are missing dependencies. So my son installed power-profiles-daemon but then he gets another error. See picture.
![D14AA15E-6C6E-4EB9-96A4-C137570AE4DC](https://user-images.githubusercontent.com/64794572/183347766-b8308698-78eb-49b3-9fb8-c3b087bb83b5.jpeg)

What goes wrong? 

Can you help?

**Comment by AdnanHodzic** [comment]
Template issue ignored and not filled out, hence making this issue invalid, closing.

Reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
