### ISSUE TITLE
failed to install from aur

### ISSUE THREAD

**Issue by Wrizz** [AdnanHodzic/auto-cpufreq#43]
install: cannot stat 'auto-cpufreq.py': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: auto-cpufreq-git

I got this error, is there a fix?

**Comment by AdnanHodzic** [comment]
@crian is the maintainer of AUR package, so could you please both gives an update? Also, I remember somewhere you mentioned it would be if there were releases, now [there are as I released v1.0](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/1.0).

@Wrizz until there's an update to AUR package, I'd suggest you to use [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq#installing-auto-cpufreq) and please inform me if you get any issues.

I also released [ `auto-cpufreq` to Snap store.](https://snapcraft.io/auto-cpufreq/) But since I see latest version of [snapd in AUR is 2.43](https://aur.archlinux.org/packages/snapd/), and as [I stated for full functionality](https://github.com/AdnanHodzic/auto-cpufreq#snap-store) `auto-cpufreq` needs snapd version 2.4.4 which is currently only available in Ubuntu 20.04.

**Comment by crian** [comment]
AUR package has been updated to the latest upstream changes.

**Comment by AdnanHodzic** [comment]
@crian great, thank you!

@Wrizz please retry by installing latest version of [auto-cpufreq AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=auto-cpufreq&outdated=&SB=n&SO=a&PP=50&do_Search=Go).

**Comment by Wrizz** [comment]
thanks, it installed without problems :)

**Comment by AdnanHodzic** [comment]
Great to hear, in that closing the issue :)
