### ISSUE TITLE
Config file not working and fan blowing all the time

### ISSUE THREAD

**Issue by Monta02** [AdnanHodzic/auto-cpufreq#470]
Fan won’t stop working even if the cores are at 30°C. I tried using a config file (copied from the one you ship) but as soon as I place it in /etc the program start spamming in the console “Using settings defined in /etc/auto-cpufreq.conf file”, and the behaviour of the fan doesn’t change at all.

**Comment by AdnanHodzic** [comment]
Template issue ignored and not filled out, hence making this issue invalid, closing.

Reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.
