### ISSUE TITLE
[Request] Instructions on how to exit "auto-cpufreq --log" 

### ISSUE THREAD

**Issue by innovaitec** [AdnanHodzic/auto-cpufreq#57]
It would be nice if there are some kind of message about how to exit "auto-cpufreq --log". Ctrl+C is working but it is not intuitive for new users.

**Comment by AdnanHodzic** [comment]
Note added as part of [1.6.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/v1.6.0). 

I even re-wrote whole auto-cpufreq with multithreading in mind so this certain key could be detected (i.e: q, esc, etc) and app would quit. But due to lack of support for [keyboard input for window in focus of keyboard python library](https://github.com/boppreh/keyboard/issues/413), this feature will be pushed in one of the future releases.
