### ISSUE TITLE
Install on an immutable system? 

### ISSUE THREAD

**Issue by ripplingsnake** [AdnanHodzic/auto-cpufreq#625]
Hello not a bug but do you know of anyway I can install this on an immutable os  ? The install fails due to insufficient rights

**Comment by AdnanHodzic** [comment]
No, and since it's not reported as a proper issue (template no filled out) I'll close it. This should go into [Discussions.](https://github.com/AdnanHodzic/auto-cpufreq/discussions).

Regarding immutable OS suport, it's [been long supported (since v1.9.7).](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/v1.9.7). But, there have been a lot of changes since then and recently in #574 there are some [mentions on how to make it work noways.](https://github.com/AdnanHodzic/auto-cpufreq/issues/574#issuecomment-1820388536).

I would suggest creating a proper issue with all needed info where it be tracked (feel free referencing to this one or fill out the template I'll re-open this issue), and then if you or anyone else who uses one immutable distros and wants to give it a try in implementing this functionality, please give it a try and [contribute to the project](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution) and you will be credited for your work as part of [future release](https://github.com/AdnanHodzic/auto-cpufreq/releases).
