### ISSUE TITLE
Max frequency and gui not working

### ISSUE THREAD

**Issue by jpgjpgjpgjpg** [AdnanHodzic/auto-cpufreq#683]
Linux distro: Ubuntu 20.04 Focal Fossa
Linux kernel: 5.15.0-105-generic
Processor: 12th Gen Intel(R) Core(TM) i5-1235U
Cores: 12
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 1300 MHz
CPU min frequency: 400 MHz

Core Usage Temperature Frequency
CPU0 3.0% 45 °C 2500 MHz
CPU1 0.0% 45 °C 2500 MHz
CPU2 2.0% 48 °C 1030 MHz
CPU3 0.0% 48 °C 2500 MHz
CPU4 2.0% 48 °C 2500 MHz
CPU5 0.0% 48 °C 2500 MHz
CPU6 0.0% 48 °C 2500 MHz
CPU7 0.0% 48 °C 2500 MHz
CPU8 1.0% 48 °C 2500 MHz
CPU9 0.0% 48 °C 2500 MHz
CPU10 2.0% 49 °C 2500 MHz
CPU11 2.0% 49 °C 2500 MHz

auto-cpufreq version: 2.2.0 (git: https://github.com/AdnanHodzic/auto-cpufreq/commit/8bb7478e38f3c9ef66b5993721f489c6099d8f68)

Python: 3.8.10
psutil package: 5.9.8
platform package: 1.0.8
click package: 8.1.7
distro package: 1.9.0

Computer type: Notebook
Battery is: discharging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.15 %

Total CPU usage: 1.8 %
Total system load: 0.71
Average temp. of all cores: 47.67 °C

Currently using: powersave governor
Currently turbo boost is: off

**Comment by AdnanHodzic** [comment]
Template issue ignored and not filled out, hence making this issue invalid, closing.

Reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
