### ISSUE TITLE
Unable to resume from sleep on fedora 40

### ISSUE THREAD

**Issue by lucaboffo** [AdnanHodzic/auto-cpufreq#733]
When I put my Dell Inspiron 15 to sleep, the computer freeze and I have to restart it manually.
All start when I installed auto-cpufreq. I alredy try `auto-cpufreq --debug` and I haven't notice any error.
Please help

**Comment by AdnanHodzic** [comment]
If you want me or someone else to help you, don't ignore filling out the issue template. Hence, I'm closing this issue until you fill it out. Feel free to re-open this issue with properly filled out requested fields.

Also same issue was reported for Fedora 40 in #726. Hence, please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behavior. As this shouldn't be related auto-cpufreq.

Reference:

### Fill out informtion requested in this template, without doing so issue will be ignored & closed!

### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```
