### ISSUE TITLE
[Feature] add more info into --debug

### ISSUE THREAD

**Issue by Red-Eyed** [AdnanHodzic/auto-cpufreq#74]
Since sensors are very different across the machines I think that it would be nice to add output of `psutil.sensors_temperature()` into `get_sys_info()` function
also, we need to know the version and the way user start it (snap or directly from the git)

in general, we should add:
* sensors info
* app version info
* Is it snap or git?
* If snap -> snap version output

maybe more

**Comment by Red-Eyed** [comment]
@AdnanHodzic do you have any idea how to get snpad version from inside the snap package?

**Comment by AdnanHodzic** [comment]
FWIK, you can't do that. Because basically snap is running inside of a container, hence all the reasons snap environment has all these exceptions within auto-cpufreq, [perfect example](https://github.com/AdnanHodzic/auto-cpufreq/blob/master/source/core.py#L440). 

But since I'm pretty sure there could be a file that could have this information stored, maybe ask this same question on [snapcraft forum](forum.snapcraft.io/)?

**Comment by AdnanHodzic** [comment]
Fixed as part of [1.6.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/v1.6.0).
